### ISSUE TITLE
Supporting pre-set colours

### ISSUE THREAD

**Issue by PragmaticPhil** [KalbeAbbas/pxt-XinaBox-BM11-RGB#1]
Where we have blocks that allow users to specify colours by name ("Blue", "green") etc, please can we specify a set of pre-set colours:
Blue
Green
Red
White 
Yellow
Pink
Purple
Brown
OFF (we could call this black - I think off is better)

… please add any others that might be missing.

**Comment by KalbeAbbas** [comment]
Updated. Please check. Thanks

**Comment by PragmaticPhil** [comment]
Thanks.
If we can't use RED (as per the issue I closed) then we are going to have to choose pre-set colours we can make with just Blue and green!
So the list will change - I'll close this issue though and we can derive the final list separately
