### ISSUE TITLE
Bug - flash LED blue causes the LED to flash red

### ISSUE THREAD

**Issue by PragmaticPhil** [KalbeAbbas/pxt-XinaBox-BM11-RGB#5]
Use the Blink LED block
Set Blue as the parameter

The LED shows red

**Comment by KalbeAbbas** [comment]
Yes, did this intentionally as final version of BM11 is not in production yet.

**Comment by KalbeAbbas** [comment]
The final version would have only Green and Blue LEDs.

**Comment by PragmaticPhil** [comment]
OK, thanks :)
